### PR TITLE
Needs a readme

### PR DESCRIPTION
**Pull request by nigelbabu**
would be useful to have a quick readme explaining what it does in one line and how to install

### CODE REVIEW

**Comment by johnjohndoe** [comment]
:+1: 

Please provide installation instructions and where one can find the repository information being displayed. I am happy to review your instructions.

---

My first attempt to install the plugin was:

1) Active the _virtualenv_ for the CKAN installation

``` bash
$ . /usr/lib/ckan/default/bin/activate
```

2) Install the plugin

``` bash
$ python setup.py install
```

However, I could not find any new information being displayed on the website.

**Comment by nigelbabu** [comment]
Hi @johnjohndoe, you need to add `repo_info` to the `ckan.plugins` line in your config and restart your server. Once you confirm it works, I'll add a readme :)

**Comment by johnjohndoe** [comment]
@nigelbabu Done. But where can I see the information when everything is set up? Please add a screenshot to the `README.md`.

**Comment by nigelbabu** [comment]
Do you see it in the footer? Near the language selector?

**Comment by johnjohndoe** [comment]
No, there is nothing in the footer.

ckan-footer

I am running [CKAN 2.2.](https://github.com/ckan/ckan/tree/ckan-2.2)

**Comment by nigelbabu** [comment]
Did you remember to restart your server? And have you installed from source?

**Comment by johnjohndoe** [comment]
Yes, I installed from source and restarted Apache and the CKAN instance.

**Comment by nigelbabu** [comment]
Can you check your apache error logs to see if there are any errors?

**Comment by johnjohndoe** [comment]
The following output appears when I enable the plugin and start the server:

``` bash
$ paster serve /etc/ckan/default/development.ini
stat: cannot stat ‘.git/FETCH_HEAD’: No such file or directory
...
```

**Comment by nigelbabu** [comment]
Can you run git fetch origin in the command line once and see if that fixes the issue?

**Comment by johnjohndoe** [comment]
@nigelbabu The message `stat: cannot stat ‘.git/FETCH_HEAD’: No such file or directory` disappeared. The footer is still empty.

**Comment by nigelbabu** [comment]
Do you have a custom theme on your CKAN install?

**Comment by johnjohndoe** [comment]
No.

**Comment by nigelbabu** [comment]
This is very weird. The exact instructions work for me.

**Comment by amercader** [comment]
No longer relevant

**Pull request closed without merging**
